"""
Django settings for controle_obra project.

Generated by 'django-admin startproject' using Django 5.2.9.

Para mais informações:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================
# CONFIGURAÇÕES BÁSICAS
# ==========================

# ATENÇÃO: em produção, troque essa chave por uma segura
SECRET_KEY = 'django-insecure-cc9!bbmdtjvg=)nx2gay!@&s0jhhi(#@ll65&8$6)+ze0*scr+'

DEBUG = True

ALLOWED_HOSTS = []

# ==========================
# APLICAÇÕES
# ==========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'empresas',
    'funcionarios',
    'acessos',
]

# ==========================
# MIDDLEWARE
# ==========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controle_obra.urls'

# ==========================
# TEMPLATES
# ==========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'controle_obra.wsgi.application'

# ==========================
# BANCO DE DADOS
# ==========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==========================
# SENHAS
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================
# IDIOMA / FUSO
# ==========================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==========================
# ARQUIVOS ESTÁTICOS
# ==========================

# URL base para servir arquivos estáticos
STATIC_URL = '/static/'

# Pasta onde você colocou a imagem Leben-225.jpg
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ==========================
# ARQUIVOS DE MÍDIA (UPLOADS)
# ==========================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================
# CHAVE PRIMÁRIA PADRÃO
# ==========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
