# Generated by Django 5.2.9 on 2026-01-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='facial_data',
            field=models.JSONField(blank=True, help_text='Dados de reconhecimento facial capturados da câmera', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='facial_registered_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do registro facial', null=True),
        ),
    ]
